window.SFF_LIKE_OPTIONS = {
  names: [
  "Aaliyah",
  "Aaron",
  "Abigail",
  "Adam",
  "Addison",
  "Adrian",
  "Aiden",
  "Aimee",
  "Alan",
  "Alana",
  "Albert",
  "Alejandro",
  "Alex",
  "Alexa",
  "Alexander",
  "Alexis",
  "Alicia",
  "Alina",
  "Alison",
  "Allen",
  "Allison",
  "Alyssa",
  "Amanda",
  "Amber",
  "Amelia",
  "Amy",
  "Ana",
  "Anastasia",
  "Andre",
  "Andrea",
  "Andrew",
  "Angela",
  "Angel",
  "Anita",
  "Ann",
  "Anna",
  "Anne",
  "Annette",
  "Anthony",
  "Antonio",
  "April",
  "Archie",
  "Aria",
  "Ariana",
  "Ariel",
  "Arlene",
  "Arthur",
  "Ashley",
  "Aubrey",
  "Audrey",
  "Aurora",
  "Austin",
  "Ava",
  "Avery",
  "Barbara",
  "Barry",
  "Beatrice",
  "Becky",
  "Bella",
  "Ben",
  "Benjamin",
  "Bernice",
  "Beth",
  "Betty",
  "Beverly",
  "Blake",
  "Bob",
  "Bobby",
  "Bonnie",
  "Brad",
  "Bradley",
  "Brandi",
  "Brandon",
  "Brenda",
  "Brett",
  "Brian",
  "Brianna",
  "Bridget",
  "Britney",
  "Bruce",
  "Bryan",
  "Bryce",
  "Caleb",
  "Cameron",
  "Candace",
  "Carl",
  "Carla",
  "Carlos",
  "Carmen",
  "Carol",
  "Caroline",
  "Carolyn",
  "Carrie",
  "Casey",
  "Cassandra",
  "Catherine",
  "Cathy",
  "Chad",
  "Charlotte",
  "Chase",
  "Chelsea",
  "Cheryl",
  "Chloe",
  "Chris",
  "Christian",
  "Christina",
  "Christine",
  "Christopher",
  "Cindy",
  "Claire",
  "Clara",
  "Clarence",
  "Claudia",
  "Clayton",
  "Cliff",
  "Clifford",
  "Clint",
  "Cody",
  "Cole",
  "Colin",
  "Colleen",
  "Connie",
  "Connor",
  "Cora",
  "Corey",
  "Courtney",
  "Craig",
  "Crystal",
  "Curtis",
  "Cynthia",
  "Dale",
  "Dana",
  "Daniel",
  "Danielle",
  "Danny",
  "Darcy",
  "Darlene",
  "Darren",
  "David",
  "Dawn",
  "Dean",
  "Debbie",
  "Deborah",
  "Debra",
  "Delia",
  "Denise",
  "Dennis",
  "Derek",
  "Diana",
  "Diane",
  "Dianne",
  "Diego",
  "Dolores",
  "Dominic",
  "Donna",
  "Doris",
  "Dorothy",
  "Doug",
  "Douglas",
  "Drew",
  "Duane",
  "Dustin",
  "Dylan",
  "Earl",
  "Ebony",
  "Eddie",
  "Edgar",
  "Edith",
  "Edward",
  "Edwin",
  "Elaine",
  "Eleanor",
  "Elena",
  "Eli",
  "Eliana",
  "Elijah",
  "Elise",
  "Elizabeth",
  "Ella",
  "Ellen",
  "Ellie",
  "Elsie",
  "Emily",
  "Emma",
  "Eric",
  "Erica",
  "Erik",
  "Erin",
  "Ernest",
  "Estelle",
  "Ethan",
  "Eva",
  "Evan",
  "Eve",
  "Evelyn",
  "Everett",
  "Faith",
  "Felix",
  "Fernando",
  "Flora",
  "Floyd",
  "Frances",
  "Francis",
  "Frank",
  "Franklin",
  "Fred",
  "Frederick",
  "Gabriel",
  "Gail",
  "Gary",
  "Gavin",
  "Gene",
  "George",
  "Gerald",
  "Geraldine",
  "Gertrude",
  "Gilbert",
  "Gina",
  "Ginger",
  "Gloria",
  "Grace",
  "Grant",
  "Greg",
  "Gregory",
  "Gretchen",
  "Hailey",
  "Hannah",
  "Harold",
  "Harry",
  "Hazel",
  "Heather",
  "Heidi",
  "Helen",
  "Helena",
  "Henry",
  "Holly",
  "Hope",
  "Howard",
  "Hugh",
  "Hunter",
  "Ian",
  "Ida",
  "Iris",
  "Isaac",
  "Isabel",
  "Isabella",
  "Isaiah",
  "Ivan",
  "Jack",
  "Jackie",
  "Jacob",
  "Jacqueline",
  "Jade",
  "Jake",
  "James",
  "Jamie",
  "Jan",
  "Jane",
  "Janet",
  "Janice",
  "Jared",
  "Jason",
  "Jean",
  "Jeanne",
  "Jeff",
  "Jeffrey",
  "Jenna",
  "Jennifer",
  "Jenny",
  "Jeremy",
  "Jerome",
  "Jerry",
  "Jesse",
  "Jessica",
  "Jessie",
  "Jill",
  "Jim",
  "Jimmy",
  "Joan",
  "Joanna",
  "Jocelyn",
  "Jodi",
  "Joe",
  "Joel",
  "John",
  "Johnny",
  "Jon",
  "Jonathan",
  "Jordan",
  "Jose",
  "Joseph",
  "Josephine",
  "Josh",
  "Joshua",
  "Joy",
  "Joyce",
  "Juan",
  "Judith",
  "Judy",
  "Julia"
],
  comments: [
  "So calming",
  "Love this app",
  "Perfect for stress",
  "Helps me unwind",
  "Great haptics",
  "Beautiful visuals",
  "My go-to calm app",
  "Exactly what I needed",
  "So soothing",
  "Love the fluid visuals",
  "Helps me focus",
  "Perfect before bed",
  "Gentle and comforting",
  "Works every time",
  "Simple and effective",
  "No clutter, just calm",
  "Love Breath Reset",
  "Rain mode is amazing",
  "Heartbeat mode helps",
  "Worth every penny",
  "Best calming app",
  "Helps my anxiety",
  "Great for sensory needs",
  "My kid loves it",
  "Perfect for meltdowns",
  "So tactile",
  "No ads \u2014 thank you",
  "No subscription",
  "Honest one-time price",
  "Built with care",
  "Quality you can feel",
  "Smooth and responsive",
  "AirPlay works great",
  "Lock screen audio is perfect",
  "iPad version rocks",
  "iPhone version rocks",
  "Helps me sleep",
  "Great for winding down",
  "I use it daily",
  "Highly recommend",
  "Five stars",
  "This really helps",
  "Calming in seconds",
  "Love the hold buttons",
  "Deep Wave is my favorite",
  "Rain Drops feels good",
  "Visuals are mesmerizing",
  "Helps me breathe",
  "Guided breathing works",
  "Quick reset",
  "Perfect for busy days",
  "Helps after work",
  "Sensory-friendly",
  "Not overwhelming",
  "Feels premium",
  "Made with heart",
  "Thank you Jeremy",
  "Grateful this exists",
  "When life feels loud",
  "When I need grounding",
  "Helps me feel present",
  "Brings me back down",
  "Like a warm blanket",
  "Feels safe",
  "Easy first tap",
  "Intuitive",
  "Clean interface",
  "Easy on the eyes",
  "Lovely sounds",
  "Haptics feel real",
  "Satisfying to hold",
  "Better than scrolling",
  "Small app, big help",
  "Actually helps",
  "Does what it says",
  "Glad I downloaded",
  "Money well spent",
  "Fair Pro price",
  "Keep building",
  "Polished",
  "Thoughtful design",
  "Overstimulation relief",
  "Quiet moment creator",
  "Pause button for life",
  "Deeply relaxing",
  "Mind quiets down",
  "Calm in my pocket",
  "Pure relaxation",
  "Joy to use",
  "Brings peace",
  "Love it",
  "Thumbs up",
  "Big fan",
  "10/10",
  "Would recommend",
  "App Store gem",
  "Native iOS done right",
  "No lag",
  "Instant calm",
  "Privacy respected",
  "Made with love",
  "Self-care in an app",
  "Zero setup stress",
  "Just right",
  "Nailed it",
  "Chef's kiss",
  "Supporter",
  "Cheering you on",
  "Rooting for this app",
  "Here for it",
  "Tell everyone",
  "Daily driver",
  "Home screen worthy",
  "Ethical app",
  "No dark patterns",
  "Indie dev win",
  "Purpose-driven",
  "Calm technology",
  "Breath Reset saved my morning",
  "Stress buttons are genius",
  "Fluid canvas is art",
  "Screen time well spent",
  "Healthy habit",
  "Family approved",
  "Teen approved",
  "Easy taps",
  "Open and go",
  "Goldilocks app",
  "Benchmark for calm apps",
  "More like this please",
  "Helps me before sleep",
  "Love it before sleep",
  "Perfect before sleep",
  "Great pick before sleep",
  "Use it before sleep",
  "Calms me before sleep",
  "Works for me before sleep",
  "Helps me after work",
  "Love it after work",
  "Perfect after work",
  "Great pick after work",
  "Use it after work",
  "Calms me after work",
  "Works for me after work",
  "Helps me in the morning",
  "Love it in the morning",
  "Perfect in the morning",
  "Great pick in the morning",
  "Use it in the morning",
  "Calms me in the morning",
  "Works for me in the morning",
  "Helps me on tough days",
  "Love it on tough days",
  "Perfect on tough days",
  "Great pick on tough days",
  "Use it on tough days",
  "Calms me on tough days",
  "Works for me on tough days",
  "Helps me when anxious",
  "Love it when anxious",
  "Perfect when anxious",
  "Great pick when anxious",
  "Use it when anxious",
  "Calms me when anxious",
  "Works for me when anxious",
  "Helps me when overstimulated",
  "Love it when overstimulated",
  "Perfect when overstimulated",
  "Great pick when overstimulated",
  "Use it when overstimulated",
  "Calms me when overstimulated",
  "Works for me when overstimulated",
  "Helps me during breaks",
  "Love it during breaks",
  "Perfect during breaks",
  "Great pick during breaks",
  "Use it during breaks",
  "Calms me during breaks",
  "Works for me during breaks",
  "Helps me on weekends",
  "Love it on weekends",
  "Perfect on weekends",
  "Great pick on weekends",
  "Use it on weekends",
  "Calms me on weekends",
  "Works for me on weekends",
  "Helps me before exams",
  "Love it before exams",
  "Perfect before exams",
  "Great pick before exams",
  "Use it before exams",
  "Calms me before exams",
  "Works for me before exams",
  "Helps me during travel",
  "Love it during travel",
  "Perfect during travel",
  "Great pick during travel",
  "Use it during travel",
  "Calms me during travel",
  "Works for me during travel",
  "Helps me in waiting rooms",
  "Love it in waiting rooms",
  "Perfect in waiting rooms",
  "Great pick in waiting rooms",
  "Use it in waiting rooms",
  "Calms me in waiting rooms",
  "Works for me in waiting rooms",
  "Helps me after school",
  "Love it after school",
  "Perfect after school",
  "Great pick after school",
  "Use it after school",
  "Calms me after school",
  "Works for me after school",
  "Helps me when overwhelmed",
  "Love it when overwhelmed",
  "Perfect when overwhelmed",
  "Great pick when overwhelmed",
  "Use it when overwhelmed",
  "Calms me when overwhelmed",
  "Works for me when overwhelmed",
  "Helps me before meetings",
  "Love it before meetings",
  "Perfect before meetings",
  "Great pick before meetings",
  "Use it before meetings",
  "Calms me before meetings",
  "Works for me before meetings",
  "Helps me at night",
  "Love it at night",
  "Perfect at night",
  "Great pick at night",
  "Use it at night",
  "Calms me at night",
  "Works for me at night",
  "Helps me on rainy days",
  "Love it on rainy days",
  "Perfect on rainy days",
  "Great pick on rainy days",
  "Use it on rainy days",
  "Calms me on rainy days",
  "Works for me on rainy days",
  "Helps me before bed",
  "Love it before bed",
  "Great pick before bed",
  "Use it before bed",
  "Calms me before bed",
  "Works for me before bed",
  "Helps me on Mondays",
  "Love it on Mondays",
  "Perfect on Mondays",
  "Great pick on Mondays",
  "Use it on Mondays",
  "Calms me on Mondays",
  "Works for me on Mondays",
  "Helps me after errands",
  "Love it after errands",
  "Perfect after errands",
  "Great pick after errands",
  "Use it after errands",
  "Calms me after errands",
  "Works for me after errands",
  "Helps me during lunch",
  "Love it during lunch",
  "Perfect during lunch",
  "Great pick during lunch",
  "Use it during lunch",
  "Calms me during lunch",
  "Works for me during lunch",
  "Great Breath Reset",
  "Amazing Breath Reset",
  "Perfect Breath Reset",
  "So good Breath Reset",
  "Best part is Breath Reset",
  "Obsessed with Breath Reset",
  "Love Deep Wave",
  "Great Deep Wave",
  "Amazing Deep Wave",
  "Perfect Deep Wave",
  "So good Deep Wave",
  "Best part is Deep Wave",
  "Obsessed with Deep Wave",
  "Love Rain Drops",
  "Great Rain Drops",
  "Amazing Rain Drops",
  "Perfect Rain Drops",
  "So good Rain Drops",
  "Best part is Rain Drops",
  "Obsessed with Rain Drops",
  "Love Heartbeat",
  "Great Heartbeat",
  "Amazing Heartbeat",
  "Perfect Heartbeat",
  "So good Heartbeat",
  "Best part is Heartbeat",
  "Obsessed with Heartbeat",
  "Love Fluid Canvas",
  "Great Fluid Canvas",
  "Amazing Fluid Canvas",
  "Perfect Fluid Canvas"
]
};
